import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomQueryClientProvider from "@/context/QueryClientContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomQueryClientProvider>
          <div className="flex flex-col min-h-screen">
            <section><Header /></section>
            <main>{children}</main>
            <section className="mt-auto"><Footer /></section>
          </div>
        </CustomQueryClientProvider>
      </body>
    </html>
  );
}
